docs_dir: 'docs'
pages:
- [index.md, Home]
- [pyspaces/index.md, pyspaces]
- [pyspaces/cli.md, pyspaces, cli]
- [pyspaces/cloning.md, pyspaces, cloning]
- [pyspaces/libc.md, pyspaces, libc]
- [pyspaces/process.md, pyspaces, process]
site_name: 'Pyspaces'